# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Al3QhHyq_AKY_NBa3fpI0PlVjxcGDEfe
"""

numero_pixels = int(input(" Quantidade de Pixels: "))
representacao_linha = []


while len(representacao_linha)< numero_pixels:
    pixel_adicionado = int(input("quantidade à adicionar: "))
    representacao_linha.append(pixel_adicionado)


def encontra_maior_numero(linha_pixel):
    maior_pixel = 0

    for pixel in linha_pixel:
        if maior_pixel < pixel:
            maior_pixel = pixel 
    return maior_pixel


def quantidade_valor_pixel(maior_numero, linha_pixel):
    quantidade_vezes_pixel_repetido = 0
    quantidade_vezes_repetidas = []

    for  referencia in range(0,maior_numero):
        for pixel in linha_pixel:
            if referencia == pixel:
                quantidade_vezes_pixel_repetido+=1
        quantidade_vezes_repetidas.append(quantidade_vezes_pixel_repetido)
        quantidade_vezes_pixel_repetido = 0
    return quantidade_vezes_repetidas

def calcula_acumulativa(quantidade_vezes_repetidas):
    referencia_acumulativa = 0
    resultado_acumulativa = []
    for valor in quantidade_vezes_repetidas:
        referencia_acumulativa += valor
        resultado_acumulativa.append(referencia_acumulativa)
    
    return resultado_acumulativa

def calcula_porcentagem(acumulativas):
    porcentagens = []
    operando = acumulativas[len(acumulativas) -1]
    for acumulativa in acumulativas:
        porcentagem = acumulativa / operando
        porcentagens.append(porcentagem)
        porcentagem = 0

    return porcentagens

def valores_equalizacao(porcentagens, maior_valor):
    valores_equalizacao = []

    for porcentagem in porcentagens:
        resultado = porcentagem * maior_valor
        valores_equalizacao.append(round(resultado))
        resultado = 0

    return valores_equalizacao

def equalizador(representacao_pixel, equalizados):
    for index in range(0, len(representacao_pixel)):
        representacao_pixel[index] = equalizados[representacao_pixel[index]]

    return representacao_pixel


maior_numero = encontra_maior_numero(representacao_linha)

conta_pixels_repetidos = quantidade_valor_pixel(maior_numero+1,representacao_linha)

acumulativa_numeros_informados =  calcula_acumulativa(conta_pixels_repetidos)

porcentagem = calcula_porcentagem(acumulativa_numeros_informados)

valores_calculados = valores_equalizacao(porcentagem,maior_numero)

linha_equalizada = equalizador(representacao_linha,valores_calculados)

print(" A equalização é: " , linha_equalizada)